# Generated by Django 2.0.8 on 2018-10-26 16:01

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'GBP £')], default='GBP', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='GBP', max_digits=10)),
                ('litres', models.FloatField(blank=True, null=True)),
                ('price_per_litre_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'GBP £')], default='GBP', editable=False, max_length=3)),
                ('price_per_litre', djmoney.models.fields.MoneyField(blank=True, decimal_places=3, default=None, default_currency='GBP', max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fuel',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('miles', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Mileage',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'GBP £')], default='GBP', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='GBP', max_digits=10)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type_of_service', models.CharField(choices=[('MOT', 'MOT'), ('Annual service', 'Annual service'), ('Insurance', 'Insurance'), ('Road tax', 'Road tax'), ('Road assistance', 'Road assistance'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'GBP £')], default='GBP', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='GBP', max_digits=10)),
                ('comment', models.TextField(blank=True)),
                ('mileage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.Mileage')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=24)),
                ('registration', models.CharField(max_length=8, unique=True)),
                ('year_manufactured', models.PositiveSmallIntegerField()),
                ('cost_of_purchase_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'GBP £')], default='GBP', editable=False, max_length=3)),
                ('cost_of_purchase', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='GBP', max_digits=10)),
                ('purchased_on', models.DateField(default=datetime.datetime.utcnow)),
                ('mileage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.Mileage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vehicle'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vehicle'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='mileage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel', to='core.Mileage'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vehicle'),
        ),
    ]
