# Generated by Django 2.0.8 on 2018-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180919_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='initial_miles',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='miles',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_manufactured',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
