# Generated by Django 2.0.8 on 2018-09-19 18:16

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180919_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', '£')], default='GBP', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='litres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='price_per_litre_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', '£')], default='GBP', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', '£')], default='GBP', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', '£')], default='GBP', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_of_service',
            field=models.CharField(choices=[('MOT', 'MOT'), ('Annual service', 'Annual service'), ('Insurance', 'Insurance'), ('Road tax', 'Road tax'), ('Road assistance', 'Road assistance'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='cost_of_purchase_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', '£')], default='GBP', editable=False, max_length=3),
        ),
    ]
