# Generated by Django 2.0.8 on 2018-10-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181004_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
