# Generated by Django 2.0.8 on 2018-10-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181004_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='miles',
        ),
        migrations.RemoveField(
            model_name='mileage',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='mileage',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='service',
            name='miles',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='initial_miles',
        ),
        migrations.AddField(
            model_name='fuel',
            name='mileage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel', to='core.Mileage'),
        ),
        migrations.AddField(
            model_name='service',
            name='mileage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.Mileage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.Mileage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mileage',
            name='miles',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
